version: '3'

services:
  app:
    container_name: app-dev
    ports:
      - '3000:3000'
    volumes:
      - ./api/package.json:/usr/src/app/package.json
      - ./api/pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
      - ./api/src:/usr/src/app/src
      - api_node_modules:/usr/src/app/node_modules
    command: npm run dev

  web:
    ports:
     - '5173:5173'
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  api_node_modules:
  web_node_modules:
