version: '3'


services:
  app-v0.0.1:
    image: ${IMAGE_APP_NAME}
    env_file:
      - .env
    expose:
      - '3000'
    command: npm run start
    networks:
      - app-net
  web-v0.0.1:
    image: ${IMAGE_WEB_NAME}
    env_file:
      - ./web/.env
    expose:
      - '4000'
    command: node build
    networks:
      - app-net

networks:
  app-net:
    external:
      name: ci-cd-nodejs-starter_app-net