name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build and deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          envs: API_ENV,WEB_ENV
          script: |
            export API_ENV="${{ secrets.API_ENV }}"
            export WEB_ENV="${{ secrets.WEB_ENV }}"
            export VERSION=${{ steps.get_version.outputs.version }}
            echo "📥 Syncing with main..."
            cd ~/ci-cd-nodejs-starter
            git fetch origin main
            git reset --hard origin/main
            git clean -fd
            ls -l
            bash ./build-deploy.sh
