name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build and deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          run: run image build
          script: |
            cd ~/ci-cd-nodejs-starter
            git pull origin main
            chmod +x *.sh
            ./get-image-version.sh
            ./build-image.sh
            ./deploy-use-image.sh