name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/ci-cd-nodejs-starter
            git pull origin main
            # Rebuild and recreate containers with your override v5 file
            docker-compose -f docker-compose.yml -f docker-compose.override.v5.yml up -d --build web-v5 app-v5
